---
- hosts: all
  become: yes
  tasks:
    - name: "Add ssh key for {{ ssh_authorized_keys_user }}"
      become: true
      ansible.posix.authorized_key:
        user: "{{ ssh_authorized_keys_user }}"
        state: present
        key: "{{ item.key }}"
      with_items: "{{ ssh_authorized_keys }}"
